In [5]:
from spork_framework_2020_left import multi_case_algorithm_2020
from spork_framework_2020_loc_left import multi_case_algorithm_2020_loc

import numpy as np
import pandas as pd
from datetime import datetime, timedelta

C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [11]:
#List of parameters that feed into SPORK
storm_relative_dirs = np.asarray([355])
zdrlevs = np.asarray([3.25])
kdplevs = np.asarray([1.5])
REFlevs = np.asarray([45])
REFlev1s = np.asarray([50])
big_storms = np.asarray([300])
zero_z_triggers = np.asarray([25])
storm_to_tracks = np.asarray([-999])
years = np.asarray([2019])
months = np.asarray([6])
days = np.asarray([7])
hours = np.asarray([22])
start_mins = np.asarray([50])
durations = np.asarray([0.2])
h_calstm = np.asarray([3500])
calibrations = np.asarray([0.0])
stations = ['KBRO']

#New Parameters--these are set as defaults in the multi_case_algorithm_2020 call but can be changed
storm_motion_dir = np.asarray([240])
track_dis = np.asarray([10])
GR_mins = np.asarray([6.0])

C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [12]:
#TEST LOOP-to test modifications of the algorithm
print(datetime.utcnow())
#for i in range(len(durations)):
#Re-run: 0, 2, 4, 6, 8, 9, 10, 11 (for z thresholds), 12
#for i in [5]:
for i in [0]:
    #print(multi_case_algorithm_ML1(150,3.25,1.5,45,50,300,25,2,2013,8,10,18,0,1.0,-0.03755074,'KAKQ',4623))
    
    #tracks_dataframe, zdroutlines, col_areas, col_lon, col_storm_lon = multi_case_algorithm_ML1_devRF(storm_relative_dirs[i],3.25,1.5,REFlevs[i],REFlev1s[i],big_storms[i],70,-1,years[i],months[i],days[i],hours[i],start_mins[i],durations[i],calibrations[i],stations[i],h_calstm[i], 240, localfolder[i], track_dis=10, GR_mins=6.0)
    tracks_dataframe, zdroutlines, col_areas, col_lon, col_storm_lon = multi_case_algorithm_2020(storm_relative_dirs[i],3.25,1.5,REFlevs[i],REFlev1s[i],big_storms[i],70,-1,years[i],months[i],days[i],hours[i],start_mins[i],durations[i],calibrations[i],stations[i],h_calstm[i], 240, track_dis=10, GR_mins=6.0)

    #tracks_dataframe, zdroutlines, col_areas, col_lon, col_storm_lon = multi_case_algorithm_ML1_devLOCAL(storm_relative_dirs[i],3.25,1.5,REFlevs[i],REFlev1s[i],big_storms[i],70,storm_to_tracks[i],years[i],months[i],days[i],hours[i],start_mins[i],durations[i],calibrations[i],stations[i],h_calstm[i], localfolder[i], track_dis=10)

    tracks_dataframe.to_pickle('SPORK_RFN_2020'+str(years[i])+str(months[i])+str(days[i])+str(stations[i])+'.pkl')
print(datetime.utcnow())

C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


2021-09-25 20:38:37.984281
Downloaded KBRO20190607_225527_V06
Downloaded KBRO20190607_230148_V06
2 out of 2 files downloaded...0 errors


C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.22.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.22.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.23.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packag

File Reading
Pre-grid Organization Section
0.45211792
bad split cut
0.4468193
0.8439636
bad split cut
0.842289
1.2463989
bad split cut
1.2748642
0.44372177
bad split cut
0.44652176
1.7592163
2.3717728
3.0724413
3.950119
5.0479813
0.44830704
bad split cut
0.4465866
6.3465495
7.9100037
9.898102
12.347281
15.426804
19.300293
KDP Section
Grid Section


C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\pyart\map\gates_to_grid.py:160: DeprecationWarning: Barnes weighting function is deprecated. Please use Barnes 2 to be consistent with Pauley and Wu 1990.
  warnings.warn("Barnes weighting function is deprecated."


Gradient Analysis and Masking
[[  0   1   2 ... 497 498 499]
 [  0   1   2 ... 497 498 499]
 [  0   1   2 ... 497 498 499]
 ...
 [  0   1   2 ... 497 498 499]
 [  0   1   2 ... 497 498 499]
 [  0   1   2 ... 497 498 499]]
(500, 500)
(-98.4189682006836, 24.916000366210938, <cartopy.crs.PlateCarree object at 0x000001DB87CA8E50>)


C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\pyproj\crs\crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\pyproj\crs\crs.py:294: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  projstring = _prepare_from_string(" ".join((projstring, projkwargs)))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\pyproj\crs\crs.py:53: FutureWarning: '+init=<authority>:<co

0 storm id
-97.78679255818594 storm lon
26.798939514948593 storm lat
looks like a new cell
1 storm id
-97.899469213326 storm lon
26.832688848593712 storm lat
looks like a new cell
Testfig Saved


C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This functi

C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This functi

C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This functi

C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This functi

C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This functi

[1.93827854 1.93095044 1.13919306] shear maxes
got a close one
shape of az (89,)
points in square (900,)
got a close one
shape of az (108,)
points in square (900,)
got a close one
shape of az (80,)
points in square (900,)
[1.81350141 1.94079349 1.11102113 1.00205453 1.10309986 1.70633003] shear maxes
got a close one
shape of az (128,)
points in square (900,)
got a close one
shape of az (148,)
points in square (900,)
got a close one
shape of az (5,)
points in square (900,)
[1.77756854 2.66925662 1.00469949 1.06428719 1.49025004 1.2872956
 1.1273459  1.56604678 2.12872261] shear maxes
got a close one
shape of az (138,)
points in square (900,)
got a close one
shape of az (159,)
points in square (900,)
got a close one
shape of az (34,)
points in square (900,)
got a close one
shape of az (1,)
points in square (900,)
[1.66584255 1.06641663 2.64237496 1.35561372 1.63277505 1.72076236
 1.42633721] shear maxes
got a close one
shape of az (73,)
points in square (900,)
got a close one
shape of az

C:\Users\matts\Documents\Python Scripts\SPORK\SPORK-SPIN-Left_SPORK\spork_framework_2020_left.py:552: RuntimeWarning: invalid value encountered in double_scalars
  hail_con_centroid_lon.append(np.sum(weighted_lons_hail) / np.sum(hail_areas_arr[np.where(hail_storm_lon == max_lons_c[i[0]])]))
C:\Users\matts\Documents\Python Scripts\SPORK\SPORK-SPIN-Left_SPORK\spork_framework_2020_left.py:554: RuntimeWarning: invalid value encountered in double_scalars
  hail_con_centroid_lat.append(np.sum(weighted_lats_hail) / np.sum(hail_areas_arr[np.where(hail_storm_lon == max_lons_c[i[0]])]))
C:\Users\matts\Documents\Python Scripts\SPORK\SPORK-SPIN-Left_SPORK\spork_framework_2020_left.py:708: RuntimeWarning: invalid value encountered in double_scalars
  col_con_centroid_lon.append(np.sum(weighted_lons_col) / np.sum(col_areas_arr[np.where(col_storm_lon == max_lons_c[i[0]])]))
C:\Users\matts\Documents\Python Scripts\SPORK\SPORK-SPIN-Left_SPORK\spork_framework_2020_left.py:710: RuntimeWarning: invalid va

Figure Saved
[0, 1.9382785402131293]
[0, 1.94079348533239]
[0, 1.777568541548394]
[0, 1.6658425545487694]
File Reading
Pre-grid Organization Section
0.45562744
bad split cut
0.44757843
0.8414917
bad split cut
0.8406296
1.2466393
bad split cut
1.2757683
0.44483566
bad split cut
0.4481392
1.759407
2.3601837
3.064331
3.9484484
5.049019
0.45049286
bad split cut
0.4478302
6.347595
7.8959656
9.911484
12.339279
15.43138
19.29831
KDP Section
Grid Section


C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\pyart\map\gates_to_grid.py:160: DeprecationWarning: Barnes weighting function is deprecated. Please use Barnes 2 to be consistent with Pauley and Wu 1990.
  warnings.warn("Barnes weighting function is deprecated."


Gradient Analysis and Masking
[[  0   1   2 ... 497 498 499]
 [  0   1   2 ... 497 498 499]
 [  0   1   2 ... 497 498 499]
 ...
 [  0   1   2 ... 497 498 499]
 [  0   1   2 ... 497 498 499]
 [  0   1   2 ... 497 498 499]]
(500, 500)
(-98.4189682006836, 24.916000366210938, <cartopy.crs.PlateCarree object at 0x000001DBB2BB0090>)


C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\pyproj\crs\crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\pyproj\crs\crs.py:294: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  projstring = _prepare_from_string(" ".join((projstring, projkwargs)))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\pyproj\crs\crs.py:53: FutureWarning: '+init=<authority>:<co

2019-06-07 22:55:27.927000 st
2019-06-07 23:01:48.434000 et
2019-06-07 22:55:27.927000 st
2019-06-07 23:01:48.434000 et
1 storm id
-97.84126349443731 storm lon
26.83258428824995 storm lat
length of obs 1
(15.19821689873928, 270.1284815274988)
2 storm id
-98.03956280747892 storm lon
26.881819171011216 storm lat
looks like a new cell


C:\Users\matts\Documents\Python Scripts\SPORK\SPORK-SPIN-Left_SPORK\stormid_section_xtrap.py:173: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  stormdte = (np.datetime64(end_time) - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's')
C:\Users\matts\Documents\Python Scripts\SPORK\SPORK-SPIN-Left_SPORK\stormid_section_xtrap.py:175: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  stormdti = (np.datetime64(start_time) - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's')
C:\Users\matts\Documents\Python Scripts\SPORK\SPORK-SPIN-Left_SPORK\radar_storm_motion.py:9: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  stormdte = (np.datetime64(end_time) - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's')
C:\Users\matts\Documents\Python Scripts\SPORK\SPORK-SPIN-Left_SPORK\radar_st

Testfig Saved


C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This functi

C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This functi

C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This functi

C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This functi

C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*izip(*geom.exterior.coords))))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\shapely\ops.py:240: DeprecationWarning: This functi

[1.98287755] shear maxes
got a close one
shape of az (132,)
points in square (900,)
[1.94932709 1.76762397 1.1317353  1.96864482] shear maxes
got a close one
shape of az (114,)
points in square (900,)
got a close one
shape of az (129,)
points in square (900,)
[1.09488336 1.92621754 1.61947134 1.01521233 1.0105231  1.83191477
 1.26969923 1.38354186] shear maxes
got a close one
shape of az (7,)
points in square (900,)
got a close one
shape of az (130,)
points in square (900,)
got a close one
shape of az (201,)
points in square (900,)
got a close one
shape of az (4,)
points in square (900,)
[1.63020271 1.63009058 1.49182765 1.01744067 1.1483764  1.45850575] shear maxes
got a close one
shape of az (70,)
points in square (900,)
got a close one
shape of az (107,)
points in square (900,)
got a close one
shape of az (101,)
points in square (900,)
storm not here yet
rotation FAILED


C:\Users\matts\Documents\Python Scripts\SPORK\SPORK-SPIN-Left_SPORK\spork_framework_2020_left.py:552: RuntimeWarning: invalid value encountered in double_scalars
  hail_con_centroid_lon.append(np.sum(weighted_lons_hail) / np.sum(hail_areas_arr[np.where(hail_storm_lon == max_lons_c[i[0]])]))
C:\Users\matts\Documents\Python Scripts\SPORK\SPORK-SPIN-Left_SPORK\spork_framework_2020_left.py:554: RuntimeWarning: invalid value encountered in double_scalars
  hail_con_centroid_lat.append(np.sum(weighted_lats_hail) / np.sum(hail_areas_arr[np.where(hail_storm_lon == max_lons_c[i[0]])]))
C:\Users\matts\Documents\Python Scripts\SPORK\SPORK-SPIN-Left_SPORK\spork_framework_2020_left.py:796: RuntimeWarning: invalid value encountered in true_divide
  shaped_ang = (180-np.abs(shaped_ang))*(shaped_ang/np.abs(shaped_ang))
C:\Users\matts\AppData\Local\Continuum\anaconda3\envs\spork2020\lib\site-packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences 

[] tracking lon
[] tracking ind areas
Figure Saved
[0, 1.9828775494020154]
[1.767623973329402, 1.949327092951561]
[1.9262175393345475, 1.0948833563612967]
[1.6300905796028078, 1.6302027072245187]
Fin
2021-09-25 20:40:13.751529
